# Generated by Django 3.0.4 on 2020-05-21 15:28

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=1000, verbose_name='name')),
                ('price', models.FloatField(verbose_name='name')),
                ('file', models.FileField(blank=True, null=True, upload_to=inventory.models.upload_inventory_item_image, verbose_name='file')),
            ],
        ),
    ]
