# Generated by Django 3.0.4 on 2020-05-21 15:29

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=inventory.models.upload_inventory_item_image, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
