# Generated by Django 3.0.4 on 2020-05-21 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200521_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_stamp'),
        ),
    ]
