# Generated by Django 3.0.4 on 2020-05-21 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
    ]
