# Generated by Django 3.0.4 on 2020-05-22 12:03

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200521_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=inventory.models.upload_inventory_item_image, verbose_name='file'),
        ),
    ]
